// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATOJPCcsOClghO_ieTg86Kc6ouGO-Qwj0',
    appId: '1:270797583600:android:a324db0be08ae1f55a7e35',
    messagingSenderId: '270797583600',
    projectId: 'ploofypaws-67fcb',
    storageBucket: 'ploofypaws-67fcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClHjtI10guleuoYiW3dqhHuX_eL04vx9I',
    appId: '1:270797583600:ios:bc4a387feefc883c5a7e35',
    messagingSenderId: '270797583600',
    projectId: 'ploofypaws-67fcb',
    storageBucket: 'ploofypaws-67fcb.appspot.com',
    androidClientId: '270797583600-3diqij9vjiacrthbnv6lu9n0usrp7257.apps.googleusercontent.com',
    iosClientId: '270797583600-lhbfsmgdujb9gf3ukjgs9sa8v8of28ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.ploofypawsDoctor',
  );
}
